name: Build

on: [push, pull_request]

# add job to build sdist as well TODO

jobs:
  build_wheels_ubuntu:
    name: Build wheels on the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.0
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_windows:
    name: Build wheels on Windows Server 2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.0
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_mac:
    name: Build wheels on macOS 11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.0
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
        
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Optional, use if you use setuptools_scm
          submodules: true # Optional, use if you have submodules
  
      - name: Build SDist
        run: pipx run build --sdist
  
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

# jobs:
#   build_wheels:
#     name: Build wheels on ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-20.04, windows-2019, macos-11]

#     steps:
#       - uses: actions/checkout@v3

#       - name: Build wheels
#         uses: pypa/cibuildwheel@v2.13.0
#         # env:
#         #   CIBW_SOME_OPTION: value
#         #    ...
#         # with:
#         #   package-dir: .
#         #   output-dir: wheelhouse
#         #   config-file: "{package}/pyproject.toml"

#       - uses: actions/upload-artifact@v3
#         with:
#           path: ./wheelhouse/*.whl
